/**
 * FCWatch Overhaul — Bookmarklet Bundle Builder
 * 
 * This script reads all portable extension scripts, applies Chrome API shims,
 * and concatenates them into a single `fcwatch-overhaul-mobile.js` bundle
 * that can be loaded via a bookmarklet on iPhone Safari.
 * 
 * Usage: node build_bookmarklet.js
 */

const fs = require('fs');
const path = require('path');

const SCRIPTS_DIR = path.join(__dirname, 'scripts');
const OUTPUT_DIR = path.join(__dirname, 'bookmarklet');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'fcwatch-overhaul-mobile.js');
const LOADER_FILE = path.join(OUTPUT_DIR, 'loader.js');
const INSTALL_FILE = path.join(OUTPUT_DIR, 'index.html');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// --- 1. Build the Killswitch Shim ---
// On mobile, the extension is always enabled (no popup toggle).
// We replace chrome.storage with localStorage and skip chrome.runtime.onMessage.
const KILLSWITCH_SHIM = `
// =====================================================
// FCWatch Overhaul — Mobile Killswitch Shim
// Extension is always enabled in bookmarklet mode.
// =====================================================
(function () {
    'use strict';
    let resolveReady;
    const readyPromise = new Promise(resolve => { resolveReady = resolve; });
    window.__FCW_EXTENSION_STATE = {
        enabled: true,
        loaded: true,
        ready: readyPromise
    };
    resolveReady(true);
    console.log('[FCW Mobile] Extension shim loaded — always enabled.');
})();
`;

// --- 2. Read and Patch Scripts ---

function readScript(filename) {
    const filepath = path.join(SCRIPTS_DIR, filename);
    if (!fs.existsSync(filepath)) {
        console.warn(`[WARN] Script not found: ${filename}`);
        return '';
    }
    return fs.readFileSync(filepath, 'utf-8');
}

function patchChromeAPIs(source, filename) {
    let patched = source;

    // Replace chrome.runtime.getURL('...') with a fallback empty string
    // These are all inside try/catch blocks, so they'll safely fall back
    // But we replace them anyway for clean execution
    patched = patched.replace(
        /chrome\.runtime\.getURL\s*\(\s*['"]([^'"]+)['"]\s*\)/g,
        (match, resourcePath) => {
            // Return empty string — the try/catch around these will handle it gracefully
            console.log(`  [PATCH ${filename}] chrome.runtime.getURL('${resourcePath}') → ''`);
            return `''`;
        }
    );

    // Replace chrome.storage.local.get calls with no-op (killswitch is shimmed separately)
    patched = patched.replace(
        /chrome\.storage\.local\.get\([^)]+,\s*\([^)]*\)\s*=>\s*\{/g,
        (match) => {
            console.log(`  [PATCH ${filename}] Removed chrome.storage.local.get call`);
            return `(function(data) { /* chrome.storage shimmed out */ void(data); })({ extensionEnabled: true }); if (false) {`;
        }
    );

    // Remove chrome.runtime.onMessage listeners
    patched = patched.replace(
        /chrome\.runtime\.onMessage\.addListener\([^;]*\);/gs,
        (match) => {
            console.log(`  [PATCH ${filename}] Removed chrome.runtime.onMessage listener`);
            return '/* chrome.runtime.onMessage removed for mobile */';
        }
    );

    // Remove chrome.storage.onChanged listeners
    patched = patched.replace(
        /chrome\.storage\.onChanged\.addListener\([^;]*\);/gs,
        (match) => {
            console.log(`  [PATCH ${filename}] Removed chrome.storage.onChanged listener`);
            return '/* chrome.storage.onChanged removed for mobile */';
        }
    );

    return patched;
}

// --- 3. Read inject_sm.js to inline it ---
const INJECT_SM_SOURCE = readScript('inject_sm.js');

function inlineInjectSM(navbarSource) {
    // The navbar creates a <script> element pointing to inject_sm.js via chrome.runtime.getURL
    // We replace the entire injectSmartMenusOverride function with an inline execution
    let patched = navbarSource;

    // Find and replace the SmartMenus injection block
    patched = patched.replace(
        /const\s+injectSmartMenusOverride\s*=\s*\(\)\s*=>\s*\{[\s\S]*?injectSmartMenusOverride\(\);/,
        `
        // --- INLINED SmartMenus Override (mobile bookmarklet) ---
        (function inlineSmartMenusOverride() {
            ${INJECT_SM_SOURCE}
        })();
        `
    );

    return patched;
}

// --- 4. Build the Bundle ---
console.log('=== FCWatch Overhaul Bookmarklet Builder ===\n');

const sections = [];

// Header
sections.push(`
// =====================================================
// FCWatch Overhaul — Mobile Bookmarklet Bundle
// Auto-generated by build_bookmarklet.js
// Built: ${new Date().toISOString()}
// =====================================================
(function() {
    'use strict';
    
    // Prevent double-injection
    if (window.__FCW_BOOKMARKLET_LOADED) {
        console.log('[FCW Mobile] Already loaded, skipping.');
        return;
    }
    window.__FCW_BOOKMARKLET_LOADED = true;
    
    // Verify we're on the right site
    if (!window.location.hostname.includes('fc-watch.com')) {
        alert('FCWatch Overhaul: Please navigate to fc-watch.com first!');
        return;
    }
    
    console.log('[FCW Mobile] Injecting FCWatch Overhaul...');
    
    // Mobile detection flag — scripts can use this for conditional optimizations
    window.__FCW_IS_MOBILE = ('ontouchstart' in window) || (navigator.maxTouchPoints > 0);
    
    // Reduce particle counts on mobile for smooth FPS
    if (window.__FCW_IS_MOBILE) {
        console.log('[FCW Mobile] Mobile device detected — optimizing particle counts.');
    }
`);

// Killswitch Shim
console.log('[1/7] Adding killswitch shim...');
sections.push('\n// === KILLSWITCH SHIM ===');
sections.push(KILLSWITCH_SHIM);

// Dark UI
console.log('[2/7] Processing dark_ui.js...');
let darkUI = readScript('dark_ui.js');
darkUI = patchChromeAPIs(darkUI, 'dark_ui.js');
sections.push('\n// === DARK UI ===');
sections.push(darkUI);

// Navbar (with inject_sm inlined)
console.log('[3/7] Processing navbar.js (inlining inject_sm.js)...');
let navbar = readScript('navbar.js');
navbar = patchChromeAPIs(navbar, 'navbar.js');
navbar = inlineInjectSM(navbar);
sections.push('\n// === NAVBAR ===');
sections.push(navbar);

// iOS Suite
console.log('[4/7] Processing ios_suite.js...');
let iosSuite = readScript('ios_suite.js');
iosSuite = patchChromeAPIs(iosSuite, 'ios_suite.js');
sections.push('\n// === iOS SUITE ===');
sections.push(iosSuite);

// Inspector
console.log('[5/7] Processing inspector.js...');
let inspector = readScript('inspector.js');
inspector = patchChromeAPIs(inspector, 'inspector.js');
sections.push('\n// === INSPECTOR ===');
sections.push(inspector);

// Page-specific scripts — conditionally loaded
console.log('[6/7] Processing page-specific scripts...');

let lnySettings = readScript('lny_settings.js');
lnySettings = patchChromeAPIs(lnySettings, 'lny_settings.js');

let modernizer = readScript('modernizer.js');
modernizer = patchChromeAPIs(modernizer, 'modernizer.js');

let objectivesHub = readScript('objectives_hub.js');
objectivesHub = patchChromeAPIs(objectivesHub, 'objectives_hub.js');

sections.push(`
// === PAGE-SPECIFIC SCRIPTS (conditional) ===

// LNY Settings — only on pack simulator LNY pages
if (window.location.href.includes('/pack-simulator/') && window.location.href.includes('/lny')) {
    console.log('[FCW Mobile] Loading LNY Settings...');
    ${lnySettings}
}

// Modernizer — only on club pages
if (window.location.href.includes('/clubs/') || window.location.href.includes('/club.php') || window.location.href.includes('/myclub')) {
    console.log('[FCW Mobile] Loading Modernizer...');
    ${modernizer}
}

// Objectives Hub — only on objectives page
if (window.location.href.includes('/obj/objectives_hub')) {
    console.log('[FCW Mobile] Loading Objectives Hub...');
    ${objectivesHub}
}
`);

// Footer — success toast
console.log('[7/7] Adding success toast...');
sections.push(`
    // === SUCCESS NOTIFICATION ===
    (function showToast() {
        const toast = document.createElement('div');
        toast.id = 'fcw-mobile-toast';
        toast.innerHTML = '✨ FCWatch Overhaul Active';
        toast.style.cssText = \`
            position: fixed;
            bottom: 30px;
            left: 50%;
            transform: translateX(-50%) translateY(20px);
            background: rgba(20, 25, 35, 0.95);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            color: #fff;
            padding: 12px 24px;
            border-radius: 30px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            font-size: 14px;
            font-weight: 600;
            letter-spacing: 0.02em;
            z-index: 999999;
            box-shadow: 0 10px 30px rgba(0,0,0,0.4);
            border: 1px solid rgba(255,255,255,0.1);
            opacity: 0;
            transition: all 0.4s cubic-bezier(0.2, 0.8, 0.2, 1);
        \`;
        document.body.appendChild(toast);
        
        requestAnimationFrame(() => {
            toast.style.opacity = '1';
            toast.style.transform = 'translateX(-50%) translateY(0)';
        });
        
        setTimeout(() => {
            toast.style.opacity = '0';
            toast.style.transform = 'translateX(-50%) translateY(20px)';
            setTimeout(() => toast.remove(), 500);
        }, 3000);
    })();
    
    console.log('[FCW Mobile] All modules injected successfully!');
})();
`);

// --- 5. Write the Bundle ---
const bundle = sections.join('\n');
fs.writeFileSync(OUTPUT_FILE, bundle, 'utf-8');

const sizeKB = (Buffer.byteLength(bundle, 'utf-8') / 1024).toFixed(1);
console.log(`\n✅ Bundle written to: ${OUTPUT_FILE}`);
console.log(`   Size: ${sizeKB} KB`);

// --- 6. Check for remaining chrome.* references ---
const chromeRefs = bundle.match(/chrome\.\w+/g);
if (chromeRefs) {
    const unique = [...new Set(chromeRefs)];
    console.log(`\n⚠️  Remaining chrome.* references (${unique.length} unique):`);
    unique.forEach(ref => console.log(`   - ${ref}`));
    console.log('   (These should all be inside try/catch blocks or dead code paths)');
} else {
    console.log('\n🎉 No chrome.* references found in bundle — fully clean!');
}

// --- 7. Create Loader Script ---
const loaderCode = `javascript:(function(){if(window.__FCW_BOOKMARKLET_LOADED){alert('FCWatch Overhaul is already active!');return;}var s=document.createElement('script');s.src='https://slimerewinston.github.io/fcwatch-overhaul-mobile.js';s.onerror=function(){alert('Failed to load FCWatch Overhaul. Check your connection.');};document.head.appendChild(s);})();`;
fs.writeFileSync(LOADER_FILE, loaderCode, 'utf-8');
console.log(`\n✅ Loader written to: ${LOADER_FILE}`);

// --- 8. Create Install Page ---
const installHTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FCWatch Overhaul — Mobile Install</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #0d111a;
            color: #f0f0f5;
            padding: 20px 15px 60px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .header { text-align: center; margin-bottom: 25px; }
        h1 {
            font-size: 1.8rem;
            font-weight: 800;
            background: linear-gradient(135deg, #00ffff, #0088ff);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 8px;
        }
        .header p { color: rgba(255,255,255,0.6); font-size: 0.95rem; }
        
        .method-card {
            background: rgba(20, 25, 35, 0.8);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 20px;
            padding: 25px 20px;
            width: 100%;
            max-width: 400px;
            margin-bottom: 15px;
            box-shadow: 0 15px 35px rgba(0,0,0,0.5);
        }
        .method-card h2 {
            font-size: 1.2rem;
            color: #fff;
            margin-bottom: 15px;
            display: flex;
            align-items: center;
            gap: 8px;
        }
        .method-card h2 span { color: #00ccff; }
        
        .ios-steps { margin: 0; padding: 0; list-style: none; }
        .ios-steps li {
            position: relative;
            padding: 12px 0 12px 36px;
            border-bottom: 1px solid rgba(255,255,255,0.06);
            font-size: 0.95rem;
            color: rgba(255,255,255,0.85);
            line-height: 1.4;
        }
        .ios-steps li:last-child { border-bottom: none; }
        .ios-steps li .badge {
            position: absolute;
            left: 0;
            top: 12px;
            width: 24px;
            height: 24px;
            background: rgba(0, 200, 255, 0.15);
            color: #00ccff;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 700;
            font-size: 0.8rem;
        }
        .ios-steps strong { color: #fff; }
        
        .drag-btn, .copy-btn {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            color: #fff;
            padding: 16px 20px;
            border-radius: 14px;
            font-weight: 700;
            font-size: 1.05rem;
            text-decoration: none;
            border: none;
            width: 100%;
            margin-top: 20px;
            box-shadow: 0 8px 20px rgba(0,0,0,0.3);
            transition: transform 0.2s;
            cursor: pointer;
        }
        .drag-btn { background: linear-gradient(135deg, #ff007f, #7f00ff); box-shadow: 0 8px 20px rgba(127, 0, 255, 0.3); }
        .copy-btn { background: linear-gradient(135deg, #00ccff, #0066ff); box-shadow: 0 8px 20px rgba(0, 100, 255, 0.3); }
        .drag-btn:active, .copy-btn:active { transform: scale(0.97); }
        .copy-btn.success { background: linear-gradient(135deg, #00e676, #00b248); box-shadow: 0 8px 20px rgba(0, 230, 118, 0.3); }
        
        code {
            background: rgba(255,255,255,0.1);
            padding: 2px 6px;
            border-radius: 4px;
            font-family: monospace;
            color: #00ccff;
        }
        .divider {
            text-align: center;
            color: rgba(255,255,255,0.4);
            margin: 10px 0 15px;
            font-weight: 600;
            font-size: 0.9rem;
            text-transform: uppercase;
            letter-spacing: 2px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>✨ FCWatch Overhaul</h1>
        <p>iOS 18 Safari Installation Guide</p>
    </div>

    <!-- METHOD 1: DRAG & DROP -->
    <div class="method-card">
        <h2><span>🏆</span> Method 1: Safari Drag</h2>
        <ul class="ios-steps">
            <li>
                <div class="badge">1</div>
                <strong>Press & Hold</strong> the purple button below. Slightly drag it, and <strong>DO NOT</strong> lift your finger.
            </li>
            <li>
                <div class="badge">2</div>
                While still holding the button, use another finger to tap the <strong>Bookmarks 📖</strong> icon at the bottom of Safari.
            </li>
            <li>
                <div class="badge">3</div>
                <strong>Drop</strong> the button into your Favorites folder.
            </li>
            <li>
                <div class="badge">4</div>
                Go to <code>fc-watch.com</code>, open your bookmarks, and tap <strong>FCWatch Overhaul</strong>.
            </li>
        </ul>
        <a class="drag-btn" href="\${loaderCode}">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 9l7 7 7-7"/></svg>
            FCWatch Overhaul
        </a>
    </div>
    
    <div class="divider">OR</div>

    <!-- METHOD 2: COPY & PASTE PROOF -->
    <div class="method-card">
        <h2><span>📋</span> Method 2: Copy & Paste</h2>
        <ul class="ios-steps">
            <li>
                <div class="badge">1</div>
                Tap the blue button below to copy the magic script.
            </li>
            <li>
                <div class="badge">2</div>
                Bookmark this current page (Share → Add Bookmark).
            </li>
            <li>
                <div class="badge">3</div>
                Open Bookmarks, tap <strong>Edit</strong>, and select the bookmark you just made.
            </li>
            <li>
                <div class="badge">4</div>
                Delete the "slimerewinston..." URL completely, and <strong>Paste</strong> the code. Hit Done!
            </li>
            <li>
                <div class="badge">5</div>
                Go to <code>fc-watch.com</code>, open your bookmarks, and tap <strong>FCWatch Overhaul</strong>.
            </li>
        </ul>
        <button id="copyBtn" class="copy-btn">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
            Copy Script Code
        </button>
    </div>

    <script>
        document.getElementById('copyBtn').addEventListener('click', function() {
            // iOS 18 Safari strips the first "javascript:" when pasting into a bookmark URL field.
            // By adding it twice, Safari strips the first one, but the second one remains, fixing the bug!
            const rawCode = "\${loaderCode.replace(/"/g, '\\\\"')}";
            const safeCode = "javascript:" + rawCode;
            navigator.clipboard.writeText(safeCode).then(() => {
                const btn = this;
                btn.innerHTML = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg> Copied (Safari-proof!)';
                btn.classList.add('success');
                setTimeout(() => {
                    btn.innerHTML = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg> Copy Script Code';
                    btn.classList.remove('success');
                }, 3000);
            }).catch(err => {
                alert('Oops, clipboard failed. Please copy manually: \\n\\n' + safeCode);
            });
        });
    </script>
</body>
</html>`;

fs.writeFileSync(INSTALL_FILE, installHTML, 'utf-8');
console.log(`✅ Index page written to: ${INSTALL_FILE}`);

console.log('\n=== BUILD COMPLETE ===');
console.log('Next steps:');
console.log('1. Upload the files in the "bookmarklet" folder to your GitHub repository.');
console.log('2. Replace YOUR_GITHUB_USERNAME in build_bookmarklet.js with your actual username and rebuild!');
console.log('3. Visit your site on iPhone to install!');
